
spring:
  application:
    name: springdataredis_demo
  #redis????
  data:
    redis:
      host: localhost
      port: 6379
      #??password: 123456
      #????16????????0?????????0????
      database: 0
      jedis:
        #redis?????
        pool:
          #?????
          max-active: 8
          #???????????
          max-wait: 1ms
          #??????????
          max-idle: 4
          #??????????
          min-idle: 0
server:
  port: 80
